//
// Created by lly on 23/09/2017.
//

#ifndef VPARSER_MODULEINPUTCONSTRAINTOBJECT_H
#define VPARSER_MODULEINPUTCONSTRAINTOBJECT_H


class ModuleInputConstraintObject {

};


#endif //VPARSER_MODULEINPUTCONSTRAINTOBJECT_H
